### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by gawdsed** [MerlijnWajer/Simba#513]
Hello, 

I've been trying to build a new version of Simba and I am getting the following fatal errors:

simba.package_components.pas(77,15) Error: function header doesn't match the previous declaration "DrawCellText(LongInt;LongInt;TRect;TGridDrawState;AnsiString);"

grids.pas(4740,23) Error: Found declaration: DrawCellText(LongInt;LongInt;TRect;TGridDrawState;const AnsiString);

Am I doing something wrong or is there a outlining problem? I tried re-downloading the project, fairly certain I'm following the build guide to a T.

**Comment by ollydev** [comment]
Hi, I think this is because you're using Lazarus 3.0 RC1 this code-breaking bug was fixed in RC2.
So you can use [Lazarus 3.0 RC2](https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2064%20bits/Lazarus%203.0RC2/) or just add `const` to the function it's complaining on. 
`procedure DrawCellText(aCol, aRow: Integer; aRect: TRect; aState: TGridDrawState; const aText: String); override; `
and futher on in the file.
`procedure TPackageVersionGrid.DrawCellText(aCol, aRow: Integer; aRect: TRect; aState: TGridDrawState; const aText: String);`

**Comment by gawdsed** [comment]
upgrade like you mentioned worked, not sure how I downloaded an older version. 

Thanks for the reply, now to migrate my scripts over from 1400 to 2000 :)
